### ISSUE TITLE
Assets for "first quick game"

### ISSUE THREAD

**Issue by iox** [flossmanualsfr/escoria#6]
Hi!

I have been going through the escoria book. Nice work! Thanks a lot!

I have a question. In the book two game projects are mentioned:
-  an example game called "first quick game"
-  another game called Escoria in Daïza to show some cool feature of Escoria and make us this week more fun (this repository)

Then it says about the "first quick game":

>  To start we prepared some files for you :
> -  the assets so that you can follow this section with the same ressources and get at the end something similar
> -  the first quick game complete project done so that you can have a look at the files if necessary

Is that "asset package" available somewhere? If not, that's no problem. I would just like to correct the book, so future readers are not confused :).

Thanks again!

**Comment by nylnook** [comment]
Hi iox !
I believe it was done... but it's probably not linked ! @kdltr do you still have it ?

**Comment by nylnook** [comment]
up @kdltr ;)

**Comment by nylnook** [comment]
Just realized that there is a separate branch for this...
you can download all the assets with this link : https://github.com/flossmanualsfr/escoria/archive/first-quick-game.zip
I updated the book accordingly.

**Comment by iox** [comment]
Thanks!!!
