### ISSUE TITLE
resource_queue.gd using VS.sync wrong

### ISSUE THREAD

**Issue by tofuhead** [flossmanualsfr/escoria#7]
in the demo game, in file resource_queue.gd there is function call VS.sync()  but this doesn't work.. 
none of the resources loaded.  all I got was blank screen.. 
I looked at the escoria framework and in there the same line is done like this: 
VS.call("sync") # workaround because sync is a keyword

I changed it like that in demo game, and it started working.. 

.b

**Comment by Sslaxx** [comment]
This is on line 94 of resource_queue.gd: `VS.sync()`

It causes a "Expected identifier as member" error message in the debugger. As @tofuhead notes above, the framework repo has `VS.call("sync")` instead.

This has been tested with the current Git build of Godot.

**Comment by Sslaxx** [comment]
Also reported on the command line:

SCRIPT ERROR: GDScript::reload: Parse Error: Expected identifier as member
   At: res://globals/resource_queue.gd:94.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gd_script.cpp:621.

**Comment by nylnook** [comment]
@punto- corrected that... Thanks for reporting !
